# Generated by Django 5.0.1 on 2024-01-24 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UgcNetExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('subject', models.CharField(max_length=60)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=50)),
                ('session', models.CharField(choices=[('June', 'June'), ('December', 'December')], max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GateExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Computer Science & Information Technology', 'Computer Science & Information Technology'), ('Data Science and Artificial Intelligence', 'Data Science and Artificial Intelligence')], max_length=255)),
                ('noofshift', models.IntegerField(choices=[(1, 1), (2, 2)], default=1)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=10)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'unique_together': {('subject', 'shift')},
            },
        ),
        migrations.CreateModel(
            name='GateAIRvsMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('min_air', models.IntegerField()),
                ('max_air', models.IntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.gateexam')),
            ],
        ),
        migrations.CreateModel(
            name='GateQualifyMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('GENERAL', 'GENERAL'), ('OBC(NCL)', 'OBC(NCL)'), ('EWS', 'EWS'), ('SC', 'SC'), ('ST', 'ST'), ('PWD', 'PWD')], max_length=20)),
                ('marks', models.FloatField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.gateexam')),
            ],
        ),
        migrations.CreateModel(
            name='UgcNetAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=30)),
                ('answer', models.CharField(max_length=10)),
                ('paper', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('positive_marks', models.IntegerField(default=0)),
                ('negative_marks', models.IntegerField(default=0)),
                ('ugcnetexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.ugcnetexam')),
            ],
        ),
        migrations.CreateModel(
            name='UgcNetExpectedCutOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('jrf', models.CharField(max_length=15)),
                ('assistant_professor', models.CharField(max_length=15)),
                ('ugcnetexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.ugcnetexam')),
            ],
        ),
        migrations.CreateModel(
            name='UgcNetStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='dinesh@turingcode.in', max_length=254)),
                ('mobile', models.IntegerField()),
                ('otp', models.IntegerField()),
                ('email_verify', models.BooleanField(default=0)),
                ('application_no', models.CharField(max_length=50)),
                ('candidate_name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=50)),
                ('test_date', models.CharField(max_length=50)),
                ('test_time', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('total_marks', models.IntegerField(default=0)),
                ('question_attempted', models.IntegerField(default=0)),
                ('correct_question', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('ugcnetexam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.ugcnetexam')),
            ],
        ),
        migrations.CreateModel(
            name='GateAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_no', models.IntegerField()),
                ('q_type', models.CharField(choices=[('MCQ', 'MCQ'), ('MSQ', 'MSQ'), ('NAT', 'NAT')], max_length=5)),
                ('answer', models.CharField(max_length=20)),
                ('marks', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('negative_marks', models.FloatField(choices=[(0, 0), (0.33, 0.33), (0.33, 0.33)])),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.gateexam')),
            ],
            options={
                'unique_together': {('exam', 'q_no')},
            },
        ),
        migrations.CreateModel(
            name='GateStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('subject', models.CharField(choices=[('Computer Science & Information Technology', 'Computer Science & Information Technology'), ('Data Science and Artificial Intelligence', 'Data Science and Artificial Intelligence')], max_length=100)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon')], max_length=10)),
                ('positive_marks', models.FloatField(default=0, max_length=100)),
                ('negative_marks', models.FloatField(default=0, max_length=100)),
                ('total_marks', models.FloatField(default=0, max_length=100)),
                ('attempted', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('incorrect', models.IntegerField(default=0)),
                ('gatescore', models.IntegerField()),
                ('response', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rank.gateexam')),
            ],
            options={
                'unique_together': {('email', 'subject', 'shift')},
            },
        ),
    ]
