# Generated by Django 5.0.1 on 2024-02-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gateairvsmarks',
            old_name='max_air',
            new_name='air',
        ),
        migrations.RemoveField(
            model_name='gateairvsmarks',
            name='min_air',
        ),
        migrations.AddField(
            model_name='gateexam',
            name='mean_top_marks',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gateanswerkey',
            name='negative_marks',
            field=models.FloatField(choices=[(0, 0), (0.33, 0.33), (0.66, 0.66)]),
        ),
    ]
