# Generated by Django 5.0.1 on 2024-02-14 09:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turing', '0002_alter_testinstruction_instruction_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject_name',
            field=models.CharField(choices=[('CS Computer Science and Information Technology', 'CS Computer Science and Information Technology'), ('Computer Science', 'Computer Science'), ('Paper - 1', 'Paper - 1'), ('Paper - 2', 'Paper - 2'), ('Computer Science and Applications', 'Computer Science and Applications'), ('Data Science and Artificial Intelligence', 'Data Science and Artificial Intelligence'), ('Programming and Data Structures', 'Programming and Data Structures'), ('Computer Organization & Architecture', 'Computer Organization & Architecture'), ('Theory of Computation', 'Theory of Computation'), ('Compiler Design', 'Compiler Design'), ('Database Management System', 'Database Management System'), ('Digital Logic', 'Digital Logic'), ('Computer Networks', 'Computer Networks'), ('Operating System', 'Operating System'), ('Algorithms', 'Algorithms'), ('Discrete and Engineering Mathematics', 'Discrete and Engineering Mathematics'), ('General Aptitude', 'General Aptitude'), ('Discrete Structures and Optimization', 'Discrete Structures and Optimization'), ('Computer System Architecture', 'Computer System Architecture'), ('Programming Languages and Computer Graphics', 'Programming Languages and Computer Graphics'), ('System Software and Operating System', 'System Software and Operating System'), ('Software Engineering', ' Software Engineering'), ('Data Structures and Algorithms', 'Data Structures and Algorithms'), ('Theory of Computation and Compilers', 'Theory of Computation and Compilers'), ('Data Communication and Computer Networks', 'Data Communication and Computer Networks'), ('Artificial Intelligence (AI)', 'Artificial Intelligence (AI)'), ('Python', 'Python')], max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='paper_name',
            field=models.CharField(choices=[('CS Computer Science and Information Technology', 'CS Computer Science and Information Technology'), ('Computer Science', 'Computer Science'), ('Paper - 1', 'Paper - 1'), ('Paper - 2', 'Paper - 2'), ('Computer Science and Applications', 'Computer Science and Applications'), ('Data Science and Artificial Intelligence', 'Data Science and Artificial Intelligence'), ('Programming and Data Structures', 'Programming and Data Structures'), ('Computer Organization & Architecture', 'Computer Organization & Architecture'), ('Theory of Computation', 'Theory of Computation'), ('Compiler Design', 'Compiler Design'), ('Database Management System', 'Database Management System'), ('Digital Logic', 'Digital Logic'), ('Computer Networks', 'Computer Networks'), ('Operating System', 'Operating System'), ('Algorithms', 'Algorithms'), ('Discrete and Engineering Mathematics', 'Discrete and Engineering Mathematics'), ('General Aptitude', 'General Aptitude'), ('Discrete Structures and Optimization', 'Discrete Structures and Optimization'), ('Computer System Architecture', 'Computer System Architecture'), ('Programming Languages and Computer Graphics', 'Programming Languages and Computer Graphics'), ('System Software and Operating System', 'System Software and Operating System'), ('Software Engineering', ' Software Engineering'), ('Data Structures and Algorithms', 'Data Structures and Algorithms'), ('Theory of Computation and Compilers', 'Theory of Computation and Compilers'), ('Data Communication and Computer Networks', 'Data Communication and Computer Networks'), ('Artificial Intelligence (AI)', 'Artificial Intelligence (AI)'), ('Python', 'Python')], max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='question_options',
            name='option',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='testseries',
            name='about',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='subject_name',
            field=models.CharField(choices=[('CS Computer Science and Information Technology', 'CS Computer Science and Information Technology'), ('Computer Science', 'Computer Science'), ('Paper - 1', 'Paper - 1'), ('Paper - 2', 'Paper - 2'), ('Computer Science and Applications', 'Computer Science and Applications'), ('Data Science and Artificial Intelligence', 'Data Science and Artificial Intelligence'), ('Programming and Data Structures', 'Programming and Data Structures'), ('Computer Organization & Architecture', 'Computer Organization & Architecture'), ('Theory of Computation', 'Theory of Computation'), ('Compiler Design', 'Compiler Design'), ('Database Management System', 'Database Management System'), ('Digital Logic', 'Digital Logic'), ('Computer Networks', 'Computer Networks'), ('Operating System', 'Operating System'), ('Algorithms', 'Algorithms'), ('Discrete and Engineering Mathematics', 'Discrete and Engineering Mathematics'), ('General Aptitude', 'General Aptitude'), ('Discrete Structures and Optimization', 'Discrete Structures and Optimization'), ('Computer System Architecture', 'Computer System Architecture'), ('Programming Languages and Computer Graphics', 'Programming Languages and Computer Graphics'), ('System Software and Operating System', 'System Software and Operating System'), ('Software Engineering', ' Software Engineering'), ('Data Structures and Algorithms', 'Data Structures and Algorithms'), ('Theory of Computation and Compilers', 'Theory of Computation and Compilers'), ('Data Communication and Computer Networks', 'Data Communication and Computer Networks'), ('Artificial Intelligence (AI)', 'Artificial Intelligence (AI)'), ('Python', 'Python')], max_length=60),
        ),
    ]
